build:
  frame: false
  transparent: true
main:
  title: ktop
  width: 100
  height: 100
  bgcolor: transparent
  bgimage: ''
  position:
    - 0
    - 0
cpu:
  textsize: 12
  textsizeh: 12
  textstyle: ''
  textcolor: white
  textcolorh: white
  textbold: '400'
  textboldh: '400'
  bgcolor: 'rgba(0,0,0)'
  bgcolorh: 'rgba(0,0,0)'
  opacity: 1
  radius: 0
memory:
  textsize: 12
  textsizeh: 12
  textstyle: ''
  textcolor: white
  textcolorh: white
  textbold: '400'
  textboldh: '400'
  bgcolor: 'rgba(0,0,0)'
  bgcolorh: 'rgba(0,0,0)'
  opacity: 1
  radius: 0
