width: 600
height: 300
cpuTextColor: white
memoryTextColor: white
backgroundColor: rgba(0,0,0)
backgroundCpu: rgba(0,0,0)
backgroundMemory: rgba(0,0,0)
backgroundImg: null
frame: false
transparent: true
position:
  - 10%
  - 10%