---
  build: 
    frame: false
    transparent: true
  main: 
    title: "ktop"
    width: 542
    height: 300
    bgcolor: "transparent"
    alwaysOnTop: true
    opendevtool: true
    resizable: false
    bgimage: ""
    position: 
      - 290
      - 309
