---
  build: 
    frame: false
    transparent: true
  main: 
    title: "ktop"
    maxWidth: 542
    maxHeight: 300
    minWidth: 96
    minHeight: 28
    bgcolor: "transparent"
    alwaysOnTop: true
    resizable: false
    bgimage: ""
    position: 
      - 690
      - 64
